// Datos del viaje. Todo lo editable vive aquí.
// Coordenadas de "Tus lugares" vienen de los links de Google Maps que pasaste.
// ponytail: un solo archivo de datos; si crece mucho, dividir por pantalla.

const TRIP = {
  start: '2026-10-24', end: '2026-11-08', people: 2,
  base: { name: '1 Waterview Dr', city: 'Danbury, CT', lat: 41.391, lng: -73.504, maps: 'https://www.google.com/maps/search/?api=1&query=1+Waterview+Drive+Danbury+CT' },
  danbury: { name: 'Danbury Station', lat: 41.3952, lng: -73.448 },
  gct: { name: 'Grand Central Terminal', lat: 40.7527, lng: -73.9772 },
  flights: [
    { date: '2026-10-24', from: 'SJO', to: 'JFK', flight: 'JetBlue 1794', dep: '13:55', arr: '20:59', terminal: 'Main' },
    { date: '2026-11-08', from: 'JFK', to: 'FLL', flight: 'JetBlue 0001', dep: '06:00', arr: '09:00', terminal: '5' },
    { date: '2026-11-08', from: 'FLL', to: 'SJO', flight: 'JetBlue 0039', dep: '12:00', arr: '13:59', terminal: '3' },
  ],
  confirmation: 'SKZNYU',
};

// Metro-North Danbury Branch · vigente 4 oct 2026 (mta.info). "c" = cambio de tren en South Norwalk.
const TRAINS = {
  fare: { peak: 20.75, offpeak: 15.25, weekly: 145, dayWeekday: 37.25, dayWeekend: 30.5, zone: 42 },
  weekday: {
    toNYC: [['05:28','07:32'],['06:12','08:08'],['06:48','08:49','c'],['07:28','09:38','c'],['07:28','09:43'],['07:51','09:55','c'],['09:03','11:23','c'],['10:30','12:52','c'],['12:03','14:22','c'],['13:27','15:54','c'],['15:27','17:53','c'],['17:18','19:26','c'],['18:45','21:42','c'],['22:32','00:52']],
    toDanbury: [['06:16','08:40','c'],['08:02','10:10','c'],['09:35','11:40','c'],['11:04','13:09','c'],['13:04','15:08','c'],['15:05','17:07','c'],['16:13','18:30','c'],['17:14','19:15'],['17:53','19:51'],['18:17','20:22'],['18:55','20:55','c'],['20:01','22:10'],['23:28','01:29','c']],
  },
  weekend: {
    toNYC: [['06:08','08:17'],['07:33','10:15','c'],['10:33','12:46','c'],['13:33','15:46','c'],['16:33','18:47','c'],['19:33','21:46','c'],['23:25','01:46']],
    toDanbury: [['08:02','10:13','c'],['11:02','13:11','c'],['14:02','16:11','c'],['15:45','17:48'],['17:02','19:11','c'],['19:34','21:39','c'],['21:02','23:11','c'],['23:28','01:29','c']],
  },
  link: 'https://www.mta.info/schedules/metro-north/danbury',
};

const CROWD = { Baja: 'var(--green)', Moderada: 'var(--sand)', Alta: 'var(--acc2)', 'Muy alta': '#C23B2E' };

// cat → tags de filtro
const CAT_TAGS = {
  'Café': ['Comida'], Comida: ['Comida'], Pizza: ['Comida'], Almuerzo: ['Comida'], Cena: ['Comida'], Mercado: ['Comida','Compras'],
  Museo: ['Cultura'], Parque: ['Cultura','Fotografía'], Mirador: ['Fotografía'], Barrio: ['Cultura','Fotografía','Compras'], Paseo: ['Cultura','Fotografía'],
  Compras: ['Compras'], Bar: ['Nocturno'], Jazz: ['Nocturno','Cultura'], Club: ['Nocturno'], Rooftop: ['Nocturno','Fotografía'], Teatro: ['Nocturno','Cultura'],
  Comedia: ['Nocturno'], Foto: ['Fotografía'], Tránsito: [], Landmark: ['Cultura','Fotografía'], Biblioteca: ['Cultura'], Hotel: [],
};

const G = (q) => 'https://www.google.com/maps/search/?api=1&query=' + encodeURIComponent(q);

// id, name, cat, hood, addr, lat, lng, rating, price, crowd, dur(min), cost($/persona), mine(de tu lista), maps, desc, hours, best, booking, tip, forecast(7 franjas 09→21, 0-4)
const PLACES = [
  // ── Tus lugares ──
  { id: 'greatlawn', name: 'The Great Lawn', cat: 'Parque', hood: 'Central Park', addr: 'Central Park, entre 79 y 85 St', lat: 40.7816915, lng: -73.9664192, rating: 4.8, price: 'Gratis', crowd: 'Moderada', dur: 60, cost: 0, mine: true, maps: 'https://www.google.com/maps/place/The+Great+Lawn/@40.7816915,-73.9664192,17z', desc: 'El gran césped de Central Park con el skyline de Midtown al sur y el castillo Belvedere al borde. A finales de octubre los olmos están en pleno color.', hours: '06:00 — 01:00', best: '10:00 — 12:00', booking: 'No aplica', tip: 'Entra por la 81 St (Museo de Historia Natural) y camina hacia Belvedere: la mejor vista del lawn con el skyline detrás.', forecast: [1,1,2,2,2,2,1] },
  { id: 'queensbridge', name: 'Queensbridge Park', cat: 'Mirador', hood: 'Long Island City', addr: 'Vernon Blvd & 41st Ave, Queens', lat: 40.7566667, lng: -73.9486111, rating: 4.6, price: 'Gratis', crowd: 'Baja', dur: 45, cost: 0, mine: true, maps: 'https://www.google.com/maps/place/Queensbridge+Park/@40.7566667,-73.9486111,17z', desc: 'Parque bajo el puente de Queensboro con vista frontal al skyline de Midtown y Roosevelt Island. Casi sin turistas; es el "Manhattanhenge" barato.', hours: '06:00 — 22:00', best: 'Atardecer y hora azul', booking: 'No aplica', tip: 'Llega 30 min antes del atardecer y quédate hasta que enciendan el puente: la foto es a la hora azul.', forecast: [0,1,1,1,2,2,1] },
  { id: 'moma', name: 'MoMA', cat: 'Museo', hood: 'Midtown', addr: '11 W 53rd St', lat: 40.7614327, lng: -73.9776216, rating: 4.7, price: '$$', crowd: 'Alta', dur: 150, cost: 30, mine: true, maps: 'https://www.google.com/maps/place/MoMA/@40.7614327,-73.9776216,17z', desc: 'La colección moderna más importante del mundo: Van Gogh, Picasso, Warhol, Monet en una sola tarde. Pisos 4 y 5 son la prioridad.', hours: '10:30 — 17:30 (sáb hasta 19:00)', best: 'Apertura 10:30 o después de 15:00', booking: 'Entrada con horario · moma.org · $30', tip: 'Empieza por el piso 5 y baja. El jardín de esculturas es gratis para sentarse a mitad de visita.', forecast: [0,3,4,4,3,3,0] },
  { id: 'tudor', name: 'Tudor City Bridge', cat: 'Foto', hood: 'Midtown East', addr: 'E 42nd St & Tudor City Pl', lat: 40.7491203, lng: -73.9704982, rating: 4.7, price: 'Gratis', crowd: 'Baja', dur: 20, cost: 0, mine: true, maps: 'https://www.google.com/maps/place/Tudor+City+Bridge/@40.7491203,-73.9704982,17z', desc: 'Puente peatonal sobre la 42 St con el Chrysler Building enmarcado al fondo. La toma clásica de la calle 42, a cinco minutos de Grand Central.', hours: 'Siempre', best: 'Mañana (luz desde el este) o hora azul', booking: 'No aplica', tip: 'Usa el lado sur del puente y espera a que un taxi amarillo cruce el encuadre.', forecast: [1,1,1,1,2,2,1] },
  { id: 'pavillon', name: 'Le Pavillon', cat: 'Cena', hood: 'Midtown East', addr: 'One Vanderbilt, 42nd St', lat: 40.7528047, lng: -73.9784677, rating: 4.6, price: '$$$', crowd: 'Moderada', dur: 90, cost: 95, mine: true, maps: 'https://www.google.com/maps/place/Le+Pavillon/@40.7528047,-73.9784677,17z', desc: 'Daniel Boulud dentro de One Vanderbilt: jardín interior, mariscos y verduras, a un minuto de Grand Central. La cena perfecta antes del tren.', hours: '17:00 — 22:00', best: '19:00 (dos horas antes del tren)', booking: 'Necesaria · Resy · 2 personas', tip: 'Pide la mesa junto a los olivos. El menú prix fixe es la forma razonable de comer aquí.', forecast: [0,0,0,0,2,3,3] },
  { id: 'snfl', name: 'SNFL · Stavros Niarchos Library', cat: 'Biblioteca', hood: 'Midtown', addr: '455 5th Ave', lat: 40.7518974, lng: -73.9818374, rating: 4.7, price: 'Gratis', crowd: 'Baja', dur: 45, cost: 0, mine: true, maps: 'https://www.google.com/maps/place/Stavros+Niarchos+Foundation+Library+(SNFL)/@40.7518974,-73.9818374,17z', desc: 'Biblioteca pública con terraza en la azotea (piso 7) abierta a todos: vista del Empire State y la 5ª Avenida, gratis y sin fila.', hours: '10:00 — 20:00 (dom 13:00 — 17:00)', best: 'Mañana', booking: 'No aplica', tip: 'Sube directo al piso 7 por el ascensor; el café de la terraza acepta tarjeta.', forecast: [1,1,1,2,2,1,0] },
  { id: 'edge', name: 'Edge Observatory', cat: 'Mirador', hood: 'Hudson Yards', addr: '30 Hudson Yards', lat: 40.7534782, lng: -74.0010393, rating: 4.7, price: '$$$', crowd: 'Alta', dur: 75, cost: 42, mine: true, maps: 'https://www.google.com/maps/place/Edge+Observatory/@40.7534782,-74.0010393,17z', desc: 'Plataforma exterior en voladizo a 345 m, piso de vidrio, vista 360° del Empire State, el Hudson y Downtown. El mirador con más vértigo de la ciudad.', hours: '10:00 — 22:00', best: 'Entrar 45 min antes del atardecer', booking: 'Necesaria · edgenyc.com · horario fijo', tip: 'Compra el horario de 17:00 el domingo 25 (atardecer 18:00): ves día, dorado y noche con una sola entrada.', forecast: [1,2,2,2,3,4,3] },
  { id: 'fragrance', name: 'Flower District · Fragrance Plants & Flowers', cat: 'Compras', hood: 'Chelsea', addr: 'W 28th St entre 6ª y 7ª Av', lat: 40.7468375, lng: -73.9920752, rating: 4.5, price: 'Gratis', crowd: 'Baja', dur: 25, cost: 0, mine: true, maps: 'https://www.google.com/maps/place/Fragrance+Plants+%26+Flowers+Inc/@40.7468375,-73.9920752,17z', desc: 'La cuadra del Flower District: las aceras de la 28 St se llenan de plantas y flores desde las 6 de la mañana. Fragrance es una de las tiendas clásicas.', hours: 'Lun — Sáb 06:00 — 15:00 · dom cerrado', best: 'Antes de las 11:00 entre semana', booking: 'No aplica', tip: 'Es una calle de mayoristas: ve temprano, la mitad cierra a mediodía.', forecast: [2,2,1,0,0,0,0] },
  { id: 'lindustrie', name: "L'industrie Pizzeria", cat: 'Pizza', hood: 'West Village', addr: '104 Christopher St', lat: 40.7332224, lng: -74.0049081, rating: 4.7, price: '$', crowd: 'Alta', dur: 35, cost: 9, mine: true, maps: "https://www.google.com/maps/place/L%E2%80%99industrie+Pizzeria+-+West+Village/@40.7332224,-74.0049081,17z", desc: 'Para muchos la mejor porción de la ciudad: masa fina y crujiente, burrata slice, tiramisú. La sucursal del Village tiene menos fila que la de Williamsburg.', hours: '11:00 — 23:00', best: 'Entre 14:30 y 16:30', booking: 'No aplica', tip: 'Pide la burrata slice y la de vodka. La fila avanza rápido, no te asustes.', forecast: [0,1,3,3,2,3,2] },
  { id: 'chinatown', name: 'Chinatown', cat: 'Barrio', hood: 'Lower Manhattan', addr: 'Canal · Mott · Doyers St', lat: 40.7157509, lng: -73.9970307, rating: 4.6, price: 'Gratis', crowd: 'Alta', dur: 75, cost: 0, mine: true, maps: 'https://www.google.com/maps/place/Chinatown,+New+York/@40.7157509,-73.9970307,16z', desc: 'Mott St, Doyers St (la curva más fotografiada de Downtown), Columbus Park con los ajedrecistas y las panaderías de Bayard St.', hours: 'Siempre', best: '11:00 — 13:00', booking: 'No aplica', tip: 'Doyers St a mediodía tiene la luz lateral; Nom Wah Tea Parlor (1920) para dim sum si hay hueco.', forecast: [1,2,3,3,3,2,2] },
  { id: 'stonest', name: 'Stone St', cat: 'Barrio', hood: 'Financial District', addr: 'Stone St, NY 10004', lat: 40.7040321, lng: -74.0115947, rating: 4.6, price: '$$', crowd: 'Moderada', dur: 60, cost: 28, mine: true, maps: 'https://www.google.com/maps/place/Stone+St,+New+York,+NY+10004/@40.7040321,-74.0115947,17z', desc: 'La calle adoquinada más antigua de Manhattan, cerrada al tráfico y llena de mesas largas. Almuerzo con cerveza entre rascacielos.', hours: 'Restaurantes 11:30 — 23:00', best: '12:30 (viernes es el día animado)', booking: 'No necesaria', tip: "Adrienne's Pizzabar para una pizza rectangular compartida; pide mesa afuera si hay sol.", forecast: [0,1,3,2,2,3,2] },
  { id: 'greenmarket', name: 'Whitehall Ferry Greenmarket', cat: 'Mercado', hood: 'Financial District', addr: '4 South St, Whitehall Terminal', lat: 40.7009696, lng: -74.0130471, rating: 4.5, price: '$', crowd: 'Baja', dur: 30, cost: 8, mine: true, maps: 'https://www.google.com/maps/place/Staten+Island+Ferry+Whitehall+Terminal+Greenmarket/@40.7009696,-74.0130471,17z', desc: 'Mercado de granjeros frente a la terminal del ferry: manzanas de Hudson Valley, sidra, donas de sidra. Solo abre los viernes.', hours: 'Viernes 08:00 — 15:00', best: 'Viernes antes del ferry', booking: 'No aplica', tip: 'Compra sidra caliente y donas para tomar en la cubierta del ferry.', forecast: [1,1,1,1,0,0,0] },
  { id: 'bbpark', name: 'Brooklyn Bridge Park', cat: 'Parque', hood: 'DUMBO · Brooklyn Heights', addr: 'Pier 1, Brooklyn', lat: 40.7022422, lng: -73.9958601, rating: 4.8, price: 'Gratis', crowd: 'Alta', dur: 75, cost: 0, mine: true, maps: 'https://www.google.com/maps/place/Brooklyn+Bridge+Park/@40.7022422,-73.9958601,16z', desc: 'Muelles sobre el East River con el skyline de Downtown enfrente y el puente encima. Pier 1 para el atardecer, Pebble Beach para la foto del Manhattan Bridge.', hours: '06:00 — 01:00', best: 'Atardecer → hora azul', booking: 'No aplica', tip: 'Baja por Washington St (DUMBO) para la foto del Manhattan Bridge y sigue al Pier 1 para el atardecer.', forecast: [1,1,2,2,3,4,3] },
  { id: 'din', name: 'Din Soup Dumplings 鼎泰轩', cat: 'Cena', hood: 'Cobble Hill · Brooklyn', addr: 'Atlantic Ave, Brooklyn', lat: 40.6941973, lng: -73.992897, rating: 4.6, price: '$$', crowd: 'Moderada', dur: 60, cost: 28, mine: true, maps: 'https://www.google.com/maps/place/Din+Soup+Dumplings/@40.6941973,-73.992897,17z', desc: 'Xiao long bao hechos a mano en Brooklyn, a 15 minutos a pie del parque del puente. Cena sin pretensiones después del atardecer en el río.', hours: '11:30 — 22:00', best: '18:30', booking: 'No necesaria · fila corta', tip: 'Pide los de cerdo y los de cangrejo; el jengibre con vinagre viene gratis.', forecast: [0,1,2,2,2,3,2] },
  { id: 'foresthills', name: 'Forest Hills Gardens', cat: 'Barrio', hood: 'Forest Hills · Queens', addr: 'Station Square, Forest Hills', lat: 40.718106, lng: -73.8448469, rating: 4.6, price: 'Gratis', crowd: 'Baja', dur: 90, cost: 0, mine: true, maps: 'https://www.google.com/maps/place/Forest+Hills,+Queens/@40.718106,-73.8448469,15z', desc: 'Barrio planificado de 1910 estilo Tudor inglés: Station Square, calles curvas, árboles enormes en color de otoño. Un pueblo dentro de Queens.', hours: 'Siempre', best: 'Tarde de domingo', booking: 'No aplica', tip: 'Llega en LIRR desde Grand Central Madison (20 min) y sal por Station Square. Austin St tiene los cafés.', forecast: [1,1,1,1,1,1,0] },
  { id: 'margon', name: 'Margon', cat: 'Almuerzo', hood: 'Midtown', addr: '136 W 46th St', lat: 40.7579064, lng: -73.9839619, rating: 4.6, price: '$', crowd: 'Moderada', dur: 40, cost: 14, mine: true, maps: 'https://www.google.com/maps/place/Margon/@40.7579064,-73.9839619,17z', desc: 'Cafetería cubana de 1972 a una cuadra de Times Square: sándwich cubano, pernil, arroz y frijoles. Barra, efectivo y rápido.', hours: 'Lun — Sáb 06:00 — 17:00 · dom cerrado', best: 'Antes de 12:30', booking: 'No aplica', tip: 'Pide el cubano y un café con leche. Cierra los domingos.', forecast: [1,2,3,3,2,0,0] },
  { id: 'django', name: 'The Django', cat: 'Jazz', hood: 'Tribeca', addr: '2 6th Ave (Roxy Hotel)', lat: 40.7194085, lng: -74.0049093, rating: 4.6, price: '$$', crowd: 'Moderada', dur: 90, cost: 35, mine: true, maps: 'https://www.google.com/maps/place/The+Django/@40.7194085,-74.0049093,17z', desc: 'Club de jazz en el sótano abovedado del Roxy Hotel, estilo cueva parisina. Sets a las 19:30 y 21:30, cócteles buenos, sin mínimo absurdo.', hours: 'Sets 19:30 / 21:30 / 23:00', best: 'Set de 19:30 (llegas al tren de 23:28)', booking: 'Recomendada · thedjangonyc.com', tip: 'Reserva el set de 19:30; desde Canal St el metro a Grand Central son 20 min.', forecast: [0,0,0,0,1,3,3] },
  { id: 'maggie', name: "Maggie Reilly's", cat: 'Bar', hood: 'Garment District', addr: 'W 35th St & 8th Ave', lat: 40.7504714, lng: -73.9982179, rating: 4.5, price: '$', crowd: 'Moderada', dur: 50, cost: 16, mine: true, maps: "https://www.google.com/maps/place/Maggie+Reilly's/@40.7504714,-73.9982179,17z", desc: 'Pub irlandés de barrio a dos cuadras de Penn Station: happy hour honesto, pintas baratas, partidos en la tele. Parada antes del tren.', hours: '11:00 — 02:00', best: 'Happy hour 16:00 — 19:00', booking: 'No aplica', tip: 'Revisa 5pm.nyc para la oferta del día; Guinness y una cesta de alitas.', forecast: [0,1,1,1,3,3,2] },
  { id: 'donutpub', name: 'The Donut Pub', cat: 'Café', hood: 'Union Square', addr: '203 W 14th St', lat: 40.7297984, lng: -73.9928956, rating: 4.6, price: '$', crowd: 'Baja', dur: 25, cost: 7, mine: true, maps: 'https://www.google.com/maps/place/The+Donut+Pub/@40.7297984,-73.9928956,17z', desc: 'Abierto 24 h desde 1964, barra de formica y donas glaseadas que no han cambiado. Desayuno de camino al Village.', hours: '24 h', best: 'Mañana', booking: 'No aplica', tip: 'Cruller glaseado y café. Efectivo o tarjeta.', forecast: [2,1,1,1,1,1,1] },
  { id: 'herald', name: 'Herald Square · Macy\'s', cat: 'Compras', hood: 'Midtown', addr: '151 W 34th St', lat: 40.750247, lng: -73.98771, rating: 4.4, price: '$$', crowd: 'Alta', dur: 60, cost: 60, mine: true, maps: 'https://www.google.com/maps/place/Herald+Square,+New+York/@40.750247,-73.98771,17z', desc: 'Macy\'s de la 34, la tienda por departamentos más grande del mundo, con las escaleras mecánicas de madera de 1902 todavía en uso.', hours: '10:00 — 22:00', best: 'Entre semana por la mañana', booking: 'No aplica', tip: 'Pide el Visitor Savings Pass (10%) en el Visitor Center del piso 1 con tu pasaporte.', forecast: [1,2,3,3,4,3,2] },
  { id: 'mamastoo', name: "Mama's TOO! West Village", cat: 'Pizza', hood: 'West Village', addr: '155 Bleecker St', lat: 40.7332891, lng: -74.0040441, rating: 4.6, price: '$', crowd: 'Alta', dur: 35, cost: 10, mine: true, maps: "https://www.google.com/maps/place/Mama's+TOO!+Pizzeria+West+Village/@40.7332891,-74.0040441,17z", desc: 'Porciones cuadradas de masa gruesa y bordes caramelizados; la square con pepperoni es la firma. Rivalidad directa con L\'industrie, que está a dos cuadras.', hours: '11:00 — 23:00', best: '19:00', booking: 'No aplica', tip: 'Ve el día que no vayas a L\'industrie: comparar las dos es el juego del Village.', forecast: [0,1,3,2,2,3,3] },
  { id: 'okiboru', name: 'Okiboru House of Tsukemen', cat: 'Almuerzo', hood: 'Lower East Side', addr: '85 Chrystie St', lat: 40.7193873, lng: -73.9897013, rating: 4.6, price: '$$', crowd: 'Moderada', dur: 50, cost: 24, mine: true, maps: 'https://www.google.com/maps/place/Okiboru+House+of+Tsukemen/@40.7193873,-73.9897013,17z', desc: 'Tsukemen (fideos gruesos para mojar en caldo denso de cerdo) al estilo Tokio. Barra pequeña, fila que se mueve.', hours: '12:00 — 22:00', best: '12:00 en punto', booking: 'No aplica', tip: 'Pide el tsukemen clásico tamaño regular; el grande es demasiado antes de caminar.', forecast: [0,1,3,2,2,3,2] },
  { id: 'lacabra', name: 'La Cabra', cat: 'Café', hood: 'NoHo', addr: '152 2nd Ave / E 7th', lat: 40.72431, lng: -73.9962, rating: 4.7, price: '$$', crowd: 'Moderada', dur: 40, cost: 14, mine: true, maps: 'https://www.google.com/maps/place/La+Cabra/@40.72431,-73.9962,17z', desc: 'Tostador danés: cardamom bun, pan de masa madre y café filtrado preciso. Luz de mañana y barra corta.', hours: '07:30 — 18:00', best: 'Antes de 10:00', booking: 'No aplica', tip: 'Pide el cardamom bun; a las 11 ya no quedan.', forecast: [2,3,2,2,2,1,0] },
  { id: 'leondore', name: 'Café Leon Dore', cat: 'Café', hood: 'Nolita', addr: '214 Mulberry St', lat: 40.7221985, lng: -73.996049, rating: 4.5, price: '$$', crowd: 'Moderada', dur: 40, cost: 12, mine: true, maps: 'https://www.google.com/maps/place/Caf%C3%A9+Leon+Dore/@40.7221985,-73.996049,17z', desc: 'El café de Aimé Leon Dore: espresso griego, freddo cappuccino, gente muy bien vestida en la acera de Mulberry St.', hours: '08:00 — 18:00', best: 'Mañana', booking: 'No aplica', tip: 'Freddo cappuccino y sentarse en la banca de afuera a mirar.', forecast: [1,2,3,3,2,1,0] },
  { id: 'deuxluxe', name: 'Deux Luxe', cat: 'Café', hood: 'Nolita', addr: 'Grand St & Mott St', lat: 40.7206081, lng: -73.9965332, rating: 4.5, price: '$$', crowd: 'Baja', dur: 40, cost: 16, mine: true, maps: 'https://www.google.com/maps/place/Deux+Luxe/@40.7206081,-73.9965332,17z', desc: 'Café-bistró pequeño en el borde de Nolita y Chinatown: pastelería, sándwiches y una barra para una pausa entre SoHo y Canal St.', hours: '08:00 — 18:00', best: 'Media mañana', booking: 'No aplica', tip: 'Buena parada antes de cruzar a Chinatown.', forecast: [1,2,2,2,1,1,0] },
  { id: 'tram', name: 'Teleférico de Roosevelt Island', cat: 'Mirador', hood: 'Upper East Side', addr: '2nd Ave & E 60th St', lat: 40.7612789, lng: -73.9641664, rating: 4.7, price: '$', crowd: 'Moderada', dur: 40, cost: 2.9, mine: true, maps: 'https://www.google.com/maps/place/Roosevelt+Island+Tramway/@40.7612789,-73.9641664,17z', desc: 'Cabina sobre el East River junto al puente de Queensboro; cuesta lo mismo que el metro (OMNY) y la vista es de helicóptero.', hours: '06:00 — 02:00 · cada 7-15 min', best: 'Atardecer', booking: 'No aplica · paga con tarjeta contactless', tip: 'Ponte en el lado norte de la cabina (lado del puente) y sigue en bus/ferry hacia Queensbridge Park.', forecast: [1,1,2,2,3,3,2] },
  { id: 'williamsburg', name: 'Williamsburg', cat: 'Barrio', hood: 'Brooklyn', addr: 'Bedford Ave · Wythe Ave · N 6th St', lat: 40.7181, lng: -73.9571, rating: 4.7, price: 'Gratis', crowd: 'Alta', dur: 120, cost: 0, mine: true, maps: G('Williamsburg Brooklyn'), desc: 'Bedford Ave para tiendas vintage, Wythe Ave para hoteles y rooftops, Domino Park para el skyline. El Brooklyn que sale en las fotos.', hours: 'Siempre', best: 'Sábado desde mediodía', booking: 'No aplica', tip: 'Domino Park al atardecer y luego la calle N 6th para cenar.', forecast: [1,2,3,3,3,4,4] },

  // ── Añadidos para cerrar las rutas ──
  { id: 'gct', name: 'Grand Central Terminal', cat: 'Landmark', hood: 'Midtown East', addr: '89 E 42nd St', lat: 40.7527, lng: -73.9772, rating: 4.7, price: 'Gratis', crowd: 'Alta', dur: 20, cost: 0, maps: G('Grand Central Terminal'), desc: 'Tu puerta de entrada cada día. El techo con constelaciones del vestíbulo principal, la galería de susurros frente al Oyster Bar y el Campbell para un cóctel antes del tren de vuelta.', hours: '05:15 — 02:00', best: 'Al llegar', booking: 'No aplica', tip: 'La galería de susurros está en el pasillo del Oyster Bar: habla a la esquina, se oye en la diagonal.', forecast: [3,3,2,2,3,3,2] },
  { id: 'belvedere', name: 'Belvedere Castle', cat: 'Mirador', hood: 'Central Park', addr: 'Mid-Park, 79th St', lat: 40.7794, lng: -73.9692, rating: 4.7, price: 'Gratis', crowd: 'Moderada', dur: 30, cost: 0, maps: G('Belvedere Castle Central Park'), desc: 'Castillo victoriano de 1869 sobre una roca con vista al Turtle Pond y al Great Lawn.', hours: '10:00 — 17:00', best: 'Mañana', booking: 'No aplica', tip: 'La terraza superior da la mejor foto del lawn con el skyline del Upper West Side.', forecast: [1,2,2,2,2,1,0] },
  { id: 'bethesda', name: 'Bethesda Terrace', cat: 'Landmark', hood: 'Central Park', addr: 'Mid-Park, 72nd St', lat: 40.774, lng: -73.9708, rating: 4.8, price: 'Gratis', crowd: 'Alta', dur: 40, cost: 0, maps: G('Bethesda Terrace'), desc: 'La fuente, la arcada con techo de azulejos Minton y el lago con los botes. El centro escénico del parque.', hours: 'Siempre', best: '11:00 — 13:00', booking: 'No aplica', tip: 'La arcada inferior tiene músicos a mediodía; sigue por el Mall hasta Literary Walk.', forecast: [1,2,3,3,3,2,1] },
  { id: 'met', name: 'The Met', cat: 'Museo', hood: 'Upper East Side', addr: '1000 5th Ave', lat: 40.7794, lng: -73.9632, rating: 4.8, price: '$$', crowd: 'Alta', dur: 150, cost: 30, maps: G('The Metropolitan Museum of Art'), desc: 'Dos millones de obras: el templo de Dendur, las armaduras, los impresionistas y la azotea. Elige tres alas y ya.', hours: '10:00 — 17:00 (vie/sáb hasta 21:00)', best: 'Después de 14:00', booking: 'Entrada en línea · $30', tip: 'Entra por la 81 St (menos fila) y empieza por Egipto; el Templo de Dendur a la luz de la tarde.', forecast: [0,3,4,4,3,2,0] },
  { id: 'levain', name: 'Levain Bakery', cat: 'Café', hood: 'Upper West Side', addr: '167 W 74th St', lat: 40.7797, lng: -73.9803, rating: 4.7, price: '$', crowd: 'Alta', dur: 20, cost: 7, maps: G('Levain Bakery 74th St'), desc: 'La galleta de chocolate con nueces de 170 g que inventó un género. Para llevar al parque.', hours: '08:00 — 20:00', best: 'Antes de 11:00', booking: 'No aplica', tip: 'Chocolate chip walnut, tibia. Una por persona basta.', forecast: [2,3,3,3,3,2,1] },
  { id: 'jacobs', name: "Jacob's Pickles", cat: 'Almuerzo', hood: 'Upper West Side', addr: '509 Amsterdam Ave', lat: 40.7865, lng: -73.9757, rating: 4.5, price: '$$', crowd: 'Alta', dur: 60, cost: 28, maps: G("Jacob's Pickles"), desc: 'Comfort food sureño del Upper West Side: biscuits, pollo frito, pickles de la casa. Almuerzo pesado antes del museo.', hours: '10:00 — 02:00', best: '13:00', booking: 'Sin reserva · espera 20 min', tip: 'Chicken & biscuit para compartir y un pickle flight.', forecast: [1,2,3,3,2,3,2] },
  { id: 'oysterbar', name: 'Grand Central Oyster Bar', cat: 'Cena', hood: 'Grand Central', addr: 'Lower Level, Grand Central', lat: 40.7526, lng: -73.9773, rating: 4.4, price: '$$$', crowd: 'Moderada', dur: 75, cost: 60, maps: G('Grand Central Oyster Bar'), desc: 'Desde 1913 bajo las bóvedas de Guastavino: ostras de media docena de estados, clam chowder y una barra que da directo al andén.', hours: 'Lun — Sáb 11:30 — 21:30', best: '19:30 antes del tren de 21:02 / 20:01', booking: 'Recomendada', tip: 'Siéntate en la barra de ostras (no el comedor): más rápido y mejor.', forecast: [0,1,2,2,2,3,2] },
  { id: 'campbell', name: 'The Campbell', cat: 'Bar', hood: 'Grand Central', addr: '15 Vanderbilt Ave', lat: 40.7526, lng: -73.9767, rating: 4.5, price: '$$$', crowd: 'Moderada', dur: 45, cost: 24, maps: G('The Campbell Bar Grand Central'), desc: 'La antigua oficina de un financiero de 1923 convertida en bar: techo pintado, chimenea, cócteles clásicos. A 3 minutos de tu andén.', hours: '12:00 — 02:00', best: 'Antes del tren de vuelta', booking: 'No necesaria', tip: 'Entra por Vanderbilt Ave; pide un Old Fashioned y mira el reloj.', forecast: [0,0,1,1,3,3,3] },
  { id: 'oculus', name: 'Oculus · WTC', cat: 'Landmark', hood: 'Financial District', addr: 'Church St & Fulton St', lat: 40.7116, lng: -74.011, rating: 4.7, price: 'Gratis', crowd: 'Alta', dur: 30, cost: 0, maps: G('Oculus World Trade Center'), desc: 'Las costillas blancas de Calatrava sobre la estación del WTC. Arquitectura para la cámara.', hours: '05:00 — 01:00', best: 'Mañana', booking: 'No aplica', tip: 'Desde el balcón del piso superior la foto simétrica sale sola.', forecast: [2,3,3,3,3,2,1] },
  { id: 'memorial', name: '9/11 Memorial', cat: 'Landmark', hood: 'Financial District', addr: '180 Greenwich St', lat: 40.7115, lng: -74.0134, rating: 4.8, price: 'Gratis', crowd: 'Alta', dur: 40, cost: 0, maps: G('9/11 Memorial'), desc: 'Las dos piscinas en la huella de las torres. El museo es aparte ($33) y pide 2 h; el memorial exterior es gratis.', hours: '08:00 — 20:00', best: 'Antes de 10:00', booking: 'Memorial sin entrada', tip: 'La pera Survivor Tree está en el lado sur.', forecast: [2,3,4,3,3,2,1] },
  { id: 'ferry', name: 'Staten Island Ferry', cat: 'Paseo', hood: 'Financial District', addr: 'Whitehall Terminal, 4 South St', lat: 40.7012, lng: -74.013, rating: 4.7, price: 'Gratis', crowd: 'Moderada', dur: 60, cost: 0, maps: G('Staten Island Ferry Whitehall Terminal'), desc: 'Gratis, cada 30 min, 25 min por trayecto y pasa frente a la Estatua de la Libertad. Ida y vuelta sin bajar es el plan.', hours: '24 h · cada 30 min', best: '13:00 — 15:00 o atardecer', booking: 'No aplica', tip: 'Ida: lado derecho (estribor) para la Estatua. Vuelta: proa para el skyline.', forecast: [1,2,2,2,3,3,2] },
  { id: 'adriennes', name: "Adrienne's Pizzabar", cat: 'Almuerzo', hood: 'Stone St', addr: '54 Stone St', lat: 40.7042, lng: -74.0105, rating: 4.5, price: '$$', crowd: 'Moderada', dur: 60, cost: 26, maps: G("Adrienne's Pizzabar"), desc: 'La pizza rectangular de Stone St, mesas en la calle adoquinada.', hours: '11:30 — 23:00', best: '12:30', booking: 'No necesaria', tip: 'Una old-fashioned para dos y ensalada.', forecast: [0,1,3,2,2,3,2] },
  { id: 'bbridge', name: 'Puente de Brooklyn a pie', cat: 'Paseo', hood: 'Manhattan → DUMBO', addr: 'Entrada por Centre St / City Hall', lat: 40.7079, lng: -73.9999, rating: 4.8, price: 'Gratis', crowd: 'Alta', dur: 45, cost: 0, maps: G('Brooklyn Bridge pedestrian entrance City Hall'), desc: '1,8 km sobre el East River por la pasarela de madera de 1883. Cruzar hacia Brooklyn tiene el skyline a la espalda y el Manhattan Bridge al lado.', hours: 'Siempre', best: 'Antes del atardecer', booking: 'No aplica', tip: 'Baja por la salida de Washington St en DUMBO para la foto clásica del Manhattan Bridge.', forecast: [2,3,3,4,4,3,2] },
  { id: 'dumbo', name: 'DUMBO · Washington St', cat: 'Foto', hood: 'DUMBO', addr: 'Washington St & Water St', lat: 40.7033, lng: -73.9897, rating: 4.7, price: 'Gratis', crowd: 'Muy alta', dur: 20, cost: 0, maps: G('Washington Street DUMBO'), desc: 'El Manhattan Bridge enmarcado entre edificios de ladrillo con el Empire State dentro del arco.', hours: 'Siempre', best: 'Atardecer', booking: 'No aplica', tip: 'Párate en el centro de la calle entre semáforos; hay fila informal para la foto.', forecast: [1,2,3,3,4,4,3] },
  { id: 'highline', name: 'The High Line', cat: 'Paseo', hood: 'Chelsea', addr: 'Entrada Gansevoort St', lat: 40.7395, lng: -74.008, rating: 4.8, price: 'Gratis', crowd: 'Alta', dur: 60, cost: 0, maps: G('The High Line Gansevoort entrance'), desc: 'Vía elevada convertida en parque lineal: 2,3 km sobre la ciudad entre galerías, el Whitney y Hudson Yards.', hours: '07:00 — 22:00', best: 'Mañana o atardecer', booking: 'No aplica', tip: 'Entra por Gansevoort y camina hacia el norte: terminas en Hudson Yards.', forecast: [1,2,3,3,4,3,2] },
  { id: 'chelseamkt', name: 'Chelsea Market', cat: 'Mercado', hood: 'Chelsea', addr: '75 9th Ave', lat: 40.7424, lng: -74.0061, rating: 4.6, price: '$$', crowd: 'Alta', dur: 60, cost: 22, maps: G('Chelsea Market'), desc: 'Mercado cubierto en la antigua fábrica de Oreo: Los Tacos No. 1, Lobster Place, Very Fresh Noodles.', hours: '08:00 — 21:00', best: 'Antes de 12:30', booking: 'No aplica', tip: 'Los Tacos No. 1 (adobada) y comer de pie; evita las 13:00.', forecast: [1,2,4,4,3,3,2] },
  { id: 'littleisland', name: 'Little Island', cat: 'Parque', hood: 'Hudson River Park', addr: 'Pier 55, W 13th St', lat: 40.742, lng: -74.0101, rating: 4.7, price: 'Gratis', crowd: 'Moderada', dur: 40, cost: 0, maps: G('Little Island NYC'), desc: 'Parque flotante sobre pilares tulipán en el Hudson. Colinas, vista a Jersey y al Downtown.', hours: '06:00 — 21:00', best: 'Atardecer', booking: 'No aplica', tip: 'Sube a la colina suroeste para el atardecer sobre el río.', forecast: [1,2,2,2,3,3,1] },
  { id: 'washsq', name: 'Washington Square Park', cat: 'Parque', hood: 'Greenwich Village', addr: 'Washington Sq N', lat: 40.7308, lng: -73.9973, rating: 4.8, price: 'Gratis', crowd: 'Moderada', dur: 45, cost: 0, maps: G('Washington Square Park'), desc: 'El arco de 1892, la fuente, pianistas, ajedrecistas y estudiantes de NYU. El mejor lugar de la ciudad para sentarse y mirar.', hours: '06:00 — 00:00', best: '14:00 — 16:00', booking: 'No aplica', tip: 'Lado noroeste de la fuente: sombra después de las 14:00 y vista al arco.', forecast: [1,2,3,3,3,2,2] },
  { id: 'comedycellar', name: 'Comedy Cellar', cat: 'Comedia', hood: 'Greenwich Village', addr: '117 MacDougal St', lat: 40.7301, lng: -74.0003, rating: 4.8, price: '$$', crowd: 'Alta', dur: 90, cost: 30, maps: G('Comedy Cellar MacDougal'), desc: 'El club de stand-up más famoso del país; los cómicos de Netflix prueban material aquí sin avisar.', hours: 'Shows 19:00 / 21:00 / 23:00', best: 'Show de 19:00', booking: 'Necesaria · comedycellar.com (se agota)', tip: 'Reserva con una semana; mínimo 2 ítems por persona.', forecast: [0,0,0,0,2,4,4] },
  { id: 'vanguard', name: 'Village Vanguard', cat: 'Jazz', hood: 'West Village', addr: '178 7th Ave S', lat: 40.736, lng: -74.0016, rating: 4.8, price: '$$$', crowd: 'Alta', dur: 90, cost: 45, maps: G('Village Vanguard'), desc: 'El sótano de jazz más importante del mundo desde 1935: Coltrane, Evans y Rollins grabaron aquí. Set de 20:00.', hours: 'Sets 20:00 / 22:00', best: 'Set de 20:00', booking: 'Necesaria · villagevanguard.com', tip: 'Llega 30 min antes: los asientos son por orden de llegada.', forecast: [0,0,0,0,1,3,4] },
  { id: 'smalls', name: 'Smalls Jazz Club', cat: 'Jazz', hood: 'West Village', addr: '183 W 10th St', lat: 40.7345, lng: -74.0024, rating: 4.7, price: '$$', crowd: 'Moderada', dur: 60, cost: 25, maps: G('Smalls Jazz Club'), desc: 'Sótano diminuto con jam sessions hasta las 3 de la mañana. La alternativa informal al Vanguard.', hours: '19:30 — 03:00', best: '22:30', booking: 'Recomendada', tip: 'Entrada vale toda la noche; entra y sal.', forecast: [0,0,0,0,1,3,4] },
  { id: 'whitney', name: 'Whitney Museum', cat: 'Museo', hood: 'Meatpacking', addr: '99 Gansevoort St', lat: 40.7396, lng: -74.0089, rating: 4.7, price: '$$', crowd: 'Moderada', dur: 120, cost: 30, maps: G('Whitney Museum of American Art'), desc: 'Arte americano del siglo XX y XXI en el edificio de Renzo Piano con terrazas sobre la High Line. Viernes de 17:00 a 22:00: paga lo que quieras.', hours: '10:30 — 18:00 (vie hasta 22:00)', best: 'Viernes 17:00 (pay what you wish)', booking: 'Entrada en línea', tip: 'Sube a la terraza del piso 8 al atardecer: el Hudson de un lado, el Empire del otro.', forecast: [0,2,3,3,3,3,2] },
  { id: 'lebain', name: 'Le Bain', cat: 'Rooftop', hood: 'Meatpacking', addr: '848 Washington St (The Standard)', lat: 40.741, lng: -74.008, rating: 4.4, price: '$$', crowd: 'Alta', dur: 75, cost: 32, maps: G('Le Bain The Standard'), desc: 'Azotea del Standard con vista 360° sobre el Hudson y Midtown. Cócteles, DJ y la ciudad encendida.', hours: '16:00 — 03:00', best: '21:00 — 22:30', booking: 'Sin reserva · fila corta antes de 22:00', tip: 'Sube antes de las 22:00; después hay fila y cover.', forecast: [0,0,0,1,2,3,4] },
  { id: 'topofrock', name: 'Top of the Rock', cat: 'Mirador', hood: 'Midtown', addr: '30 Rockefeller Plaza', lat: 40.7587, lng: -73.9787, rating: 4.8, price: '$$$', crowd: 'Muy alta', dur: 75, cost: 40, maps: G('Top of the Rock'), desc: 'La vista con el Empire State en el centro y Central Park entero al norte. Mejor que el Empire porque el Empire sale en la foto.', hours: '09:00 — 23:00', best: '45 min antes del atardecer', booking: 'Necesaria · horario fijo · topoftherocknyc.com', tip: 'Después del 1 de noviembre el atardecer es a las 16:50: compra el horario de 16:00.', forecast: [1,2,3,3,4,4,3] },
  { id: 'bryant', name: 'Bryant Park Winter Village', cat: 'Mercado', hood: 'Midtown', addr: '42nd St & 6th Ave', lat: 40.7536, lng: -73.9832, rating: 4.7, price: 'Gratis', crowd: 'Alta', dur: 45, cost: 15, maps: G('Bryant Park Winter Village'), desc: 'Pista de hielo gratis (alquiler de patines $) y casetas navideñas desde finales de octubre. Chocolate caliente entre rascacielos.', hours: '11:00 — 22:00', best: 'Noche', booking: 'No aplica · patines $', tip: 'Patinar es gratis si llevas patines; alquilar ronda $25.', forecast: [1,2,2,3,4,4,3] },
  { id: 'tkts', name: 'Broadway · TKTS', cat: 'Teatro', hood: 'Times Square', addr: 'Duffy Square, 47th & Broadway', lat: 40.759, lng: -73.9845, rating: 4.7, price: '$$$', crowd: 'Muy alta', dur: 170, cost: 95, maps: G('TKTS Times Square'), desc: 'Boletos del mismo día al 50% para funciones de 19:00/20:00. Las escaleras rojas de Duffy Square son la foto de Times Square.', hours: 'TKTS 15:00 — 20:00 · funciones 19:00/20:00', best: 'Función de 19:00 (sales 21:30 → tren 23:28)', booking: 'TKTS mismo día o app TodayTix', tip: 'Revisa la app TKTS a las 15:00 desde el tren; elige función de 19:00 para llegar al tren de 23:28.', forecast: [1,2,3,4,4,4,4] },
  { id: 'totto', name: 'Totto Ramen', cat: 'Cena', hood: "Hell's Kitchen", addr: '248 E 52nd St / 366 W 52nd', lat: 40.764, lng: -73.988, rating: 4.5, price: '$$', crowd: 'Alta', dur: 50, cost: 22, maps: G('Totto Ramen 52nd St'), desc: 'Ramen de caldo de pollo (paitan) en una barra sin ventanas. Rápido, a 10 min de los teatros.', hours: '12:00 — 23:00', best: '17:30 antes del teatro', booking: 'No aplica · fila', tip: 'Spicy chicken paitan y un huevo extra.', forecast: [0,1,3,2,3,4,3] },
  { id: 'apollo', name: 'Apollo Theater · Amateur Night', cat: 'Teatro', hood: 'Harlem', addr: '253 W 125th St', lat: 40.81, lng: -73.95, rating: 4.7, price: '$$', crowd: 'Alta', dur: 150, cost: 35, maps: G('Apollo Theater'), desc: 'Los miércoles a las 19:30 el público abuchea o consagra a los aspirantes, como con Ella Fitzgerald y James Brown. La noche más neoyorquina de la semana.', hours: 'Miércoles 19:30', best: 'Miércoles 4 de noviembre', booking: 'Necesaria · apollotheater.org', tip: 'Sales a las 22:00: la estación Harlem-125th St del Metro-North está a 10 min y el tren de 23:28 para ahí a las 23:38.', forecast: [0,0,0,0,1,4,4] },
  { id: 'redrooster', name: 'Red Rooster', cat: 'Cena', hood: 'Harlem', addr: '310 Lenox Ave', lat: 40.8083, lng: -73.9448, rating: 4.5, price: '$$$', crowd: 'Alta', dur: 90, cost: 55, maps: G('Red Rooster Harlem'), desc: 'Marcus Samuelsson: comfort food de Harlem con sello sueco-etíope, música en vivo en el sótano (Ginny\'s).', hours: '16:30 — 22:00', best: '17:30 antes del Apollo', booking: 'Necesaria · Resy', tip: 'Fried yardbird y cornbread. Reserva a las 17:30 para llegar al Apollo a las 19:15.', forecast: [0,0,1,1,3,4,3] },
  { id: 'tompkins', name: 'East Village · Tompkins Sq', cat: 'Barrio', hood: 'East Village', addr: 'Ave A & E 9th St', lat: 40.7265, lng: -73.9817, rating: 4.6, price: 'Gratis', crowd: 'Moderada', dur: 60, cost: 0, maps: G('Tompkins Square Park'), desc: 'St. Marks Pl, Ave A, tiendas de discos, izakayas y bares de dive. El barrio que no se ha gentrificado del todo.', hours: 'Siempre', best: 'Tarde → noche', booking: 'No aplica', tip: 'Veselka (24 h, pierogi ucranianos) y McSorley\'s (1854, dos cervezas por pedido).', forecast: [1,1,2,2,3,3,3] },
  { id: 'veselka', name: 'Veselka', cat: 'Cena', hood: 'East Village', addr: '144 2nd Ave', lat: 40.729, lng: -73.9873, rating: 4.5, price: '$$', crowd: 'Alta', dur: 60, cost: 24, maps: G('Veselka'), desc: 'Diner ucraniano desde 1954: pierogi, borscht, blintzes. Abierto hasta tarde.', hours: '08:00 — 23:00', best: '18:30', booking: 'No aplica', tip: 'Pierogi mixtos fritos y un borscht caliente.', forecast: [1,2,3,2,2,3,3] },
  { id: 'mcsorleys', name: "McSorley's Old Ale House", cat: 'Bar', hood: 'East Village', addr: '15 E 7th St', lat: 40.7287, lng: -73.9897, rating: 4.6, price: '$', crowd: 'Alta', dur: 45, cost: 14, maps: G("McSorley's Old Ale House"), desc: 'El bar más antiguo de la ciudad (1854): aserrín en el suelo, solo cerveza clara u oscura, de dos en dos.', hours: '11:00 — 01:00', best: 'Happy hour', booking: 'No aplica', tip: 'Pide "two light, two dark" y efectivo listo.', forecast: [0,1,2,2,3,4,4] },
  { id: 'galleries', name: 'Galerías de Chelsea', cat: 'Museo', hood: 'Chelsea', addr: 'W 24th St entre 10ª y 11ª Av', lat: 40.7487, lng: -74.0046, rating: 4.6, price: 'Gratis', crowd: 'Baja', dur: 75, cost: 0, maps: G('Gagosian 24th Street Chelsea'), desc: 'Gagosian, Pace, David Zwirner, Hauser & Wirth: museos gratis en edificios industriales. Los jueves hay inauguraciones con vino de 18:00 a 20:00.', hours: 'Mar — Sáb 10:00 — 18:00', best: 'Jueves 16:00 — 20:00', booking: 'No aplica', tip: 'Empieza en la 24 St y baja hacia la 19 St; revisa las inauguraciones del jueves en artforum.com/guide.', forecast: [0,1,1,2,2,3,1] },
  { id: 'domino', name: 'Domino Park', cat: 'Parque', hood: 'Williamsburg', addr: '15 River St, Brooklyn', lat: 40.7142, lng: -73.9679, rating: 4.7, price: 'Gratis', crowd: 'Moderada', dur: 45, cost: 0, maps: G('Domino Park'), desc: 'Antigua refinería de azúcar convertida en parque frente al Williamsburg Bridge con el skyline de Midtown enfrente.', hours: '06:00 — 23:00', best: 'Atardecer', booking: 'No aplica', tip: 'Los tacos de Tacocina dentro del parque para ver el atardecer con una michelada.', forecast: [1,1,2,3,4,3,2] },
  { id: 'sundayinbk', name: 'Sunday in Brooklyn', cat: 'Almuerzo', hood: 'Williamsburg', addr: '348 Wythe Ave', lat: 40.7145, lng: -73.963, rating: 4.5, price: '$$', crowd: 'Alta', dur: 75, cost: 32, maps: G('Sunday in Brooklyn Wythe'), desc: 'El brunch de Williamsburg: pancakes de malta con praliné de avellana. Fila los fines de semana.', hours: '09:00 — 22:00', best: '11:00 (o reserva)', booking: 'Resy · recomendada', tip: 'Los pancakes para compartir; la fila sin reserva pasa de 45 min a las 12.', forecast: [2,3,4,3,2,2,2] },
  { id: 'brooklynheights', name: 'Brooklyn Heights Promenade', cat: 'Mirador', hood: 'Brooklyn Heights', addr: 'Montague St & Pierrepont Pl', lat: 40.696, lng: -73.997, rating: 4.8, price: 'Gratis', crowd: 'Moderada', dur: 30, cost: 0, maps: G('Brooklyn Heights Promenade'), desc: 'El paseo elevado con la vista postal de Downtown Manhattan y el puente de Brooklyn.', hours: 'Siempre', best: 'Hora azul', booking: 'No aplica', tip: 'Después de Din, sube por Atlantic Ave y Hicks St: 15 min.', forecast: [1,1,2,2,3,3,2] },
  { id: 'fifthave', name: '5ª Avenida · Apple & flagships', cat: 'Compras', hood: 'Midtown', addr: '5th Ave entre 49 y 59 St', lat: 40.7636, lng: -73.9729, rating: 4.6, price: '$$$', crowd: 'Muy alta', dur: 90, cost: 100, maps: G('Apple Fifth Avenue'), desc: 'Apple del cubo, Tiffany, Saks, Nike y Uniqlo. Las vitrinas de Navidad empiezan a montarse en noviembre.', hours: '10:00 — 20:00', best: 'Sábado temprano', booking: 'No aplica', tip: 'Uniqlo y Nike en la 5ª tienen precios mejores que en Costa Rica; Saks para mirar.', forecast: [1,2,3,4,4,3,2] },
  { id: 'century21', name: 'Century 21', cat: 'Compras', hood: 'Financial District', addr: '22 Cortlandt St', lat: 40.7103, lng: -74.0098, rating: 4.3, price: '$$', crowd: 'Alta', dur: 75, cost: 80, maps: G('Century 21 Cortlandt St'), desc: 'El outlet de diseñador de Downtown, reabierto frente al WTC. Marcas a 40-70%.', hours: '10:00 — 21:00', best: 'Mañana', booking: 'No aplica', tip: 'Zapatos y abrigos son las secciones que valen la pena.', forecast: [1,2,3,3,3,3,2] },
  { id: 'strand', name: 'The Strand', cat: 'Compras', hood: 'Union Square', addr: '828 Broadway', lat: 40.7333, lng: -73.9908, rating: 4.7, price: '$', crowd: 'Moderada', dur: 45, cost: 20, maps: G('The Strand Bookstore'), desc: '18 millas de libros desde 1927. Mesa de usados a $1 en la acera y tote bags.', hours: '10:00 — 20:00', best: 'Cualquiera', booking: 'No aplica', tip: 'El piso 3 (Rare Books) está abierto al público.', forecast: [1,2,2,3,3,2,1] },
  { id: 'katz', name: "Katz's Delicatessen", cat: 'Almuerzo', hood: 'Lower East Side', addr: '205 E Houston St', lat: 40.7223, lng: -73.9874, rating: 4.6, price: '$$', crowd: 'Muy alta', dur: 45, cost: 30, maps: G("Katz's Delicatessen"), desc: 'Pastrami on rye desde 1888. Guarda el ticket que te dan al entrar o no sales.', hours: '08:00 — 23:00', best: '15:00 — 17:00', booking: 'No aplica', tip: 'Pastrami para compartir, un cutter te lo deja probar. Propina al cortador.', forecast: [1,2,4,4,3,4,3] },
  { id: 'tenement', name: 'Tenement Museum', cat: 'Museo', hood: 'Lower East Side', addr: '103 Orchard St', lat: 40.7187, lng: -73.9901, rating: 4.8, price: '$$', crowd: 'Baja', dur: 75, cost: 30, maps: G('Tenement Museum'), desc: 'Visita guiada a los apartamentos de inmigrantes de 1863 tal como vivieron. El museo que más te enseña de Nueva York por hora.', hours: '10:00 — 18:30', best: 'Tour de 14:30', booking: 'Necesaria · tenement.org · tours con horario', tip: 'Tour "Hard Times" o "Tenement Women"; reserva con una semana.', forecast: [1,2,2,2,2,1,0] },
  { id: 'nomwah', name: 'Nom Wah Tea Parlor', cat: 'Almuerzo', hood: 'Chinatown', addr: '13 Doyers St', lat: 40.7146, lng: -73.9981, rating: 4.5, price: '$$', crowd: 'Alta', dur: 50, cost: 22, maps: G('Nom Wah Tea Parlor'), desc: 'Dim sum desde 1920 en la curva de Doyers St. Mesas de formica, carta con fotos.', hours: '11:00 — 21:00', best: '11:00 en punto', booking: 'No aplica · fila', tip: 'Shrimp & snow pea leaf dumplings y el original egg roll.', forecast: [0,2,4,3,2,3,2] },
  { id: 'soho', name: 'SoHo · Cast Iron District', cat: 'Barrio', hood: 'SoHo', addr: 'Greene · Mercer · Broadway', lat: 40.7233, lng: -74.0007, rating: 4.8, price: 'Gratis', crowd: 'Alta', dur: 90, cost: 0, maps: G('Greene Street SoHo'), desc: 'La mayor concentración de arquitectura de hierro fundido del mundo: fachadas de 1870, adoquines en Greene y Mercer, flagship stores.', hours: 'Tiendas 11:00 — 19:00', best: '11:00 — 13:00', booking: 'No aplica', tip: 'Greene St entre Grand y Broome es la mejor cuadra para fotos de fachadas con luz lateral.', forecast: [1,2,3,4,4,3,2] },
  { id: 'housingworks', name: 'Housing Works Bookstore', cat: 'Compras', hood: 'SoHo', addr: '126 Crosby St', lat: 40.7244, lng: -73.9985, rating: 4.7, price: '$', crowd: 'Baja', dur: 30, cost: 10, maps: G('Housing Works Bookstore Cafe'), desc: 'Librería de segunda mano con escaleras de caracol y café; todo lo recaudado va a vivienda para personas con VIH.', hours: '11:00 — 19:00', best: 'Cualquiera', booking: 'No aplica', tip: 'Un café en el entrepiso y mirar desde arriba.', forecast: [0,1,2,2,2,2,1] },
  { id: 'moynihan', name: 'Moynihan Train Hall', cat: 'Landmark', hood: 'Penn Station', addr: '421 8th Ave', lat: 40.7519, lng: -73.9965, rating: 4.7, price: 'Gratis', crowd: 'Alta', dur: 20, cost: 0, maps: G('Moynihan Train Hall'), desc: 'El antiguo edificio de correos convertido en estación: techo de vidrio y acero, reloj central. La foto de arquitectura de Midtown West.', hours: '05:00 — 01:00', best: 'Mediodía (luz cenital)', booking: 'No aplica', tip: 'Desde el balcón del Starbucks sale la toma simétrica.', forecast: [2,3,3,3,3,3,2] },
  { id: 'gantry', name: 'Gantry Plaza State Park', cat: 'Mirador', hood: 'Long Island City', addr: '4-09 47th Rd, Queens', lat: 40.7466, lng: -73.9579, rating: 4.8, price: 'Gratis', crowd: 'Baja', dur: 45, cost: 0, maps: G('Gantry Plaza State Park'), desc: 'Las grúas Pepsi-Cola y el skyline completo de Midtown desde la otra orilla. A 15 min a pie de Queensbridge Park.', hours: '06:00 — 22:00', best: 'Hora azul', booking: 'No aplica', tip: 'El letrero de Pepsi se enciende al oscurecer.', forecast: [0,1,1,1,2,3,2] },
  { id: 'twa', name: 'TWA Hotel · JFK', cat: 'Hotel', hood: 'JFK Terminal 5', addr: 'One Idlewild Dr, JFK', lat: 40.6454, lng: -73.7781, rating: 4.5, price: '$$$', crowd: 'Baja', dur: 0, cost: 0, maps: G('TWA Hotel JFK'), desc: 'La terminal de Saarinen de 1962 convertida en hotel, conectada a pie con la Terminal 5 de JetBlue. Dormir aquí el 7 de noviembre resuelve el vuelo de las 06:00.', hours: '24 h', best: 'Noche del 7 de noviembre', booking: 'twahotel.com · ~$250-300', tip: 'Check-in tarde; la piscina infinita en la azotea mira a la pista. Caminas 5 min a la T5.', forecast: [0,0,0,0,0,0,0] },
  { id: 'wythe', name: 'Hotel en Williamsburg', cat: 'Hotel', hood: 'Williamsburg', addr: 'Wythe Ave & N 11th St', lat: 40.722, lng: -73.958, rating: 4.5, price: '$$$', crowd: 'Baja', dur: 0, cost: 0, maps: G('Wythe Hotel'), desc: 'Noche del 31 en Brooklyn: Wythe Hotel, The William Vale o Moxy Williamsburg quedan a 10 min en taxi del Brooklyn Storehouse y a 15 de Elsewhere.', hours: '24 h', best: 'Noche del 31 de octubre', booking: 'Reservar ya · Halloween se agota', tip: 'Check-in antes de las 16:00 para dejar los disfraces y volver tarde sin tren.', forecast: [0,0,0,0,0,0,0] },

  // ── Halloween · 31 de octubre ──
  { id: 'circoloco', name: 'Circoloco Halloween · Brooklyn Storehouse', cat: 'Club', hood: 'Brooklyn Navy Yard', addr: 'Building 293, Brooklyn Navy Yard', lat: 40.7014, lng: -73.9735, rating: 4.7, price: '$$$', crowd: 'Muy alta', dur: 360, cost: 120, maps: G('Brooklyn Storehouse Navy Yard'), link: 'https://www.circoloco.com', desc: 'La fiesta de Ibiza en una nave de 10.000 m² del Navy Yard. Sábado 31: Dixon, ANOTR, Jimi Jules, Rossi, KROL, Aline Umber, Jamback. 22:00 — 06:00, 21+. El viernes 30 toca Seth Troxler, Rampa, &ME, Carlita.', hours: '22:00 — 06:00', best: 'Llegar 23:30', booking: 'Necesaria · se agota · RA / circoloco.com', tip: 'Compra ya. Disfraz sí pero cómodo: 8 horas de pie. Taxi desde Williamsburg 10 min.', forecast: [0,0,0,0,0,2,4] },
  { id: 'elsewhere', name: 'Elsewhere Halloween', cat: 'Club', hood: 'Bushwick', addr: '599 Johnson Ave, Brooklyn', lat: 40.709, lng: -73.9231, rating: 4.6, price: '$$', crowd: 'Alta', dur: 300, cost: 50, maps: G('Elsewhere Bushwick'), link: 'https://www.elsewherebrooklyn.com', desc: 'Tres salas y una azotea en una antigua fábrica de muebles. Halloween con Major League DJz, SAIDAH, D Stone y más: house, afro house y disco. Menos masivo que Circoloco, más fiesta de barrio.', hours: '22:00 — 04:00', best: '23:00', booking: 'Recomendada · elsewherebrooklyn.com', tip: 'La sala Zone One es la íntima; la azotea cierra temprano en octubre.', forecast: [0,0,0,0,0,2,4] },
  { id: 'nowadays', name: 'Nowadays', cat: 'Club', hood: 'Ridgewood', addr: '56-06 Cooper Ave, Queens', lat: 40.7048, lng: -73.924, rating: 4.7, price: '$$', crowd: 'Alta', dur: 300, cost: 40, maps: G('Nowadays Ridgewood'), link: 'https://nowadays.nyc', desc: 'El club de house y techno con mejor sonido y mejor público de la ciudad. Cada Halloween hace su propia fiesta ("Nowadays Halloween"); confirma el cartel en su web en octubre.', hours: '22:00 — 06:00+', best: 'Después de 01:00', booking: 'Por confirmar · nowadays.nyc', tip: 'Política estricta de no fotos. Es el plan B perfecto si Circoloco se agota.', forecast: [0,0,0,0,0,1,4] },
  { id: 'publicrecords', name: 'Public Records', cat: 'Club', hood: 'Gowanus', addr: '233 Butler St, Brooklyn', lat: 40.6806, lng: -73.9896, rating: 4.6, price: '$$', crowd: 'Alta', dur: 240, cost: 40, maps: G('Public Records Brooklyn'), link: 'https://publicrecords.nyc', desc: 'Sound room audiófila, restaurante vegano y jardín. House profundo y disco; Halloween suele ser dos noches. Confirmar cartel.', hours: '22:00 — 04:00', best: '23:30', booking: 'Por confirmar · publicrecords.nyc', tip: 'Cena ahí mismo antes (Public Records Kitchen) y entra sin fila.', forecast: [0,0,0,0,0,2,4] },
  { id: 'phd', name: 'PHD Rooftop · Dream Downtown', cat: 'Rooftop', hood: 'Meatpacking', addr: '355 W 16th St, piso 12', lat: 40.7418, lng: -74.0045, rating: 4.4, price: '$$$', crowd: 'Alta', dur: 150, cost: 60, maps: G('PHD Rooftop Lounge Dream Downtown'), link: 'https://nychalloweenparties.com/halloween-at-phd-rooftop-in-the-dream-downtown/', desc: 'Rooftop con vista al Empire State y el Hudson. Sábado 31, 22:00 — 04:00, open bar patrocinado 22:00 — 23:00. DJs open format y electrónica; disfraz muy recomendado, 21+.', hours: '22:00 — 04:00', best: '22:00 (open bar)', booking: 'Necesaria · entradas en línea', tip: 'Pre-fiesta elegante antes de cruzar a Brooklyn: a las 00:30 un taxi al Storehouse son 20 min.', forecast: [0,0,0,0,0,2,4] },
  { id: 'refinery', name: 'Refinery Rooftop · Masquerade', cat: 'Rooftop', hood: 'Midtown', addr: '63 W 38th St', lat: 40.752, lng: -73.9853, rating: 4.4, price: '$$$', crowd: 'Alta', dur: 150, cost: 55, maps: G('Refinery Rooftop'), link: 'https://www.eventbrite.com/e/masquerade-rooftop-halloween-party-tickets-1998504951107', desc: 'Masquerade Halloween Party en la azotea del Refinery Hotel, techo retráctil con el Empire State al lado. Doors 21:00, DJ, cócteles temáticos, mesas VIP.', hours: '21:00 — 00:00', best: '21:00', booking: 'Eventbrite', tip: 'Máscara y traje: es la opción con dress code real. Termina a medianoche, ideal como primera parada.', forecast: [0,0,0,0,0,3,4] },
  { id: 'superior', name: 'Superior Ingredients Rooftop', cat: 'Rooftop', hood: 'Williamsburg', addr: '74 Wythe Ave, Brooklyn', lat: 40.7222, lng: -73.958, rating: 4.4, price: '$$', crowd: 'Alta', dur: 180, cost: 25, maps: G('Superior Ingredients Williamsburg'), link: 'https://www.alwaysthevip.com/featured-events/halloween-parties/', desc: 'Azotea acristalada con vista panorámica a Manhattan, en Williamsburg. Halloween desde las 17:00 hasta las 04:00, house y pop. A 5 min de los hoteles de Wythe Ave.', hours: '17:00 — 04:00', best: '20:00 — 23:00', booking: 'Entradas desde $20', tip: 'Es el rooftop práctico: cenas en Williamsburg, subes aquí, y al Storehouse en taxi.', forecast: [0,0,0,0,1,3,4] },
  { id: 'mrpurple', name: 'Mr. Purple', cat: 'Rooftop', hood: 'Lower East Side', addr: '180 Orchard St, piso 15', lat: 40.7217, lng: -73.9887, rating: 4.3, price: '$$', crowd: 'Alta', dur: 150, cost: 30, maps: G('Mr. Purple Hotel Indigo LES'), link: 'https://www.alwaysthevip.com/featured-events/halloween-parties/', desc: 'Rooftop del Hotel Indigo con dos pistas y vista a Downtown. Halloween 21:00 — 04:00, EDM y top 40, disfraz obligatorio en espíritu.', hours: '21:00 — 04:00', best: '21:30', booking: 'Entradas $20 — 30', tip: 'Más fiesta universitaria que club serio; úsalo si el plan es quedarse en Manhattan.', forecast: [0,0,0,0,0,3,4] },
  { id: 'parade', name: 'Village Halloween Parade', cat: 'Paseo', hood: 'Greenwich Village', addr: '6th Ave desde Spring St hasta 16th St', lat: 40.7254, lng: -74.004, rating: 4.7, price: 'Gratis', crowd: 'Muy alta', dur: 90, cost: 0, maps: G('Village Halloween Parade 6th Ave'), link: 'https://halloween-nyc.com', desc: 'El desfile de disfraces más grande del mundo, 19:00 por la 6ª Avenida. Cualquiera con disfraz puede marchar (entrada por Canal St desde las 18:30). Es el calentamiento antes de las fiestas.', hours: '19:00 — 23:00', best: 'Verlo 19:00 — 20:30 desde la 6ª Av con Bleecker', booking: 'Gratis', tip: 'Marchar es mejor que mirar: entra por 6th Ave & Canal entre 18:30 y 20:30 con disfraz. Luego taxi a Brooklyn.', forecast: [0,0,0,0,1,4,4] },
];

const BY_ID = Object.fromEntries(PLACES.map((p) => [p.id, p]));

// Días. window: full (08:00-22:00) · after (15:00-23:00) · arrival · departure. acts: [placeId, 'HH:MM']
const DAYS = [
  { date: '2026-10-24', title: 'Llegada · JFK → Danbury', window: 'arrival', acts: [], note: 'Aterrizan 20:59 en JFK. AirTrain a Jamaica (10 min) + LIRR a Grand Central Madison (35 min) llega ~22:40; el último tren a Danbury sale 23:28 y llega 01:29 con cambio en South Norwalk. Alternativa: Uber JFK → Danbury, ~1 h 20 y $150-190.' },
  { date: '2026-10-25', title: 'Midtown Este → Hudson Yards', window: 'full', acts: [['gct','10:20'],['tudor','10:45'],['snfl','11:10'],['moma','12:15'],['herald','15:00'],['moynihan','16:05'],['edge','17:00'],['pavillon','19:15']], why: 'Todo en un corredor este-oeste de la 42 St: cada tramo es de menos de 15 min a pie y terminas a un minuto del andén.' },
  { date: '2026-10-26', title: 'Central Park · UWS · Queens', window: 'full', acts: [['levain','10:15'],['greatlawn','10:50'],['belvedere','11:55'],['bethesda','12:35'],['jacobs','13:30'],['met','14:45'],['tram','17:30'],['queensbridge','18:15'],['oysterbar','19:45']], why: 'De norte a sur por el parque sin retroceder, y el teleférico cruza el río justo para el atardecer en Queens.' },
  { date: '2026-10-27', title: 'Chinatown → Lower East Side', window: 'full', acts: [['nomwah','11:00'],['chinatown','12:00'],['okiboru','13:15'],['tenement','14:30'],['katz','16:00'],['mcsorleys','17:00'],['tompkins','17:50'],['veselka','19:00']], why: 'Doyers St, Orchard St y Houston St están a cinco cuadras entre sí; es el día de caminar y comer.' },
  { date: '2026-10-28', title: 'Chelsea → West Village', window: 'full', acts: [['donutpub','09:45'],['fragrance','10:20'],['maggie','10:50'],['highline','11:45'],['chelseamkt','12:55'],['littleisland','14:05'],['lindustrie','15:00'],['washsq','15:50'],['strand','16:45'],['comedycellar','19:00']], why: 'Empiezas en la 28 St cuando el Flower District aún está abierto y bajas por la High Line hacia el Village sin repetir calle.' },
  { date: '2026-10-29', title: 'Nolita · SoHo · jazz en Tribeca', window: 'full', acts: [['lacabra','10:00'],['leondore','10:50'],['soho','11:40'],['housingworks','13:15'],['deuxluxe','13:55'],['galleries','15:30'],['mamastoo','18:00'],['django','19:30']], why: 'Cafés al abrir, SoHo antes de la multitud de la tarde, galerías el jueves (inauguraciones) y jazz a diez minutos de Canal St.' },
  { date: '2026-10-30', title: 'Downtown → Brooklyn', window: 'full', acts: [['memorial','10:15'],['oculus','11:00'],['century21','11:35'],['greenmarket','12:50'],['ferry','13:30'],['stonest','14:45'],['bbridge','16:00'],['dumbo','16:50'],['bbpark','17:15'],['din','18:45'],['brooklynheights','20:00']], why: 'El Greenmarket solo abre viernes y el ferry es gratis; cruzas el puente con el sol bajando para llegar al parque a la hora dorada.' },
  { date: '2026-10-31', title: 'Halloween · Williamsburg y Brooklyn', window: 'halloween', acts: [['sundayinbk','11:30'],['williamsburg','13:00'],['wythe','15:30'],['domino','17:00'],['parade','19:00'],['superior','21:00'],['phd','22:00'],['circoloco','23:30']], note: 'Noche en NYC: sin tren de vuelta. Hotel en Williamsburg para estar a 10 min del Storehouse.', why: 'Hotel y rooftop en la misma cuadra de Wythe Ave; el desfile y PHD son opcionales según energía. El Storehouse cierra a las 06:00.' },
  { date: '2026-11-01', title: 'Domingo lento · Forest Hills', window: 'full', acts: [['sundayinbk','11:00'],['foresthills','14:00'],['gct','17:30'],['campbell','17:45']], note: 'Termina el horario de verano: a las 02:00 los relojes retroceden una hora. Atardecer a las 16:49 desde hoy.', why: 'Después de Circoloco el día es corto: brunch tarde, Queens en LIRR (Forest Hills → Grand Central Madison son 20 min) y tren temprano.' },
  { date: '2026-11-02', title: 'After work · Rockefeller y Broadway', window: 'after', acts: [['topofrock','16:00'],['bryant','17:30'],['totto','18:00'],['tkts','19:00']], why: 'El atardecer es a las 16:49: el horario de 16:00 en Top of the Rock cubre día, dorado y noche. Función de 19:00 para llegar al tren de 23:28.' },
  { date: '2026-11-03', title: 'After work · East Village', window: 'after', acts: [['strand','16:15'],['tompkins','17:00'],['mcsorleys','18:00'],['veselka','19:00'],['smalls','20:30']], why: 'Happy hours del East Village (revisa 5pm.nyc) y jazz de sótano a quince minutos de Grand Central en metro.' },
  { date: '2026-11-04', title: 'After work · Harlem y el Apollo', window: 'after', acts: [['redrooster','17:30'],['apollo','19:30']], note: 'Vuelta desde Harlem-125th St: el tren de 23:28 a Danbury para ahí a las 23:38. No bajes a Grand Central.', why: 'Amateur Night es solo miércoles; cenas en Lenox Ave y subes al tren en la 125 St sin volver a Midtown.' },
  { date: '2026-11-05', title: 'After work · Chelsea y el Vanguard', window: 'after', acts: [['galleries','16:00'],['highline','17:15'],['chelseamkt','18:15'],['vanguard','20:00']], why: 'Jueves de inauguraciones en las galerías, atardecer en la High Line y el set de las 20:00 en el Vanguard.' },
  { date: '2026-11-06', title: 'After work · Whitney y Meatpacking', window: 'after', acts: [['whitney','17:00'],['littleisland','19:00'],['lebain','20:30']], why: 'Viernes de 17:00 a 22:00 el Whitney es pay-what-you-wish; Le Bain está a tres cuadras.' },
  { date: '2026-11-07', title: 'Compras · despedida · JFK', window: 'full', acts: [['fifthave','10:30'],['margon','12:15'],['soho','13:30'],['lindustrie','15:00'],['gantry','17:00'],['twa','20:30']], note: 'Vuelo 06:00 del domingo: dormir en el TWA Hotel (Terminal 5 de JetBlue). Desde Danbury no hay tren a esa hora.', why: 'Último día: lo que faltó comprar, la pizza de despedida y el skyline desde Queens; de LIC a JFK son 45 min en metro E + AirTrain.' },
  { date: '2026-11-08', title: 'Salida · JFK → FLL → SJO', window: 'departure', acts: [], note: 'JetBlue 0001 sale 06:00 de la Terminal 5 (llegar 04:15). Conexión en FLL: llegada 09:00, salida 12:00 de la Terminal 3. Aterrizan en SJO a las 13:59.' },
];

const WINDOWS = {
  full: { label: 'DÍA COMPLETO', start: '08:00', end: '23:30', color: 'var(--acc)' },
  after: { label: 'AFTER WORK', start: '15:00', end: '23:30', color: 'var(--turq)' },
  halloween: { label: 'HALLOWEEN · NOCHE EN NYC', start: '10:00', end: '06:00', color: '#C23B2E' },
  arrival: { label: 'LLEGADA', start: '20:59', end: '23:59', color: 'var(--sand)' },
  departure: { label: 'SALIDA', start: '04:00', end: '06:00', color: 'var(--sand)' },
};

const FILTERS = [
  ['EXPERIENCIA', ['Comida', 'Cultura', 'Compras', 'Fotografía', 'Nocturno']],
  ['PRECIO', ['Gratis', '$', '$$', '$$$']],
  ['MOMENTO', ['Mañana', 'Tarde', 'Atardecer', 'Noche']],
  ['MULTITUD', ['Baja', 'Moderada', 'Alta']],
];

const PHOTO_FILTERS = ['Atardecer', 'Amanecer', 'Hora azul', 'Noche', 'Arquitectura', 'Skyline', 'Calle'];
// Spots de foto: placeId, kind, tags, stars, cuando (clave de SUN o hora fija)
const PHOTO_SPOTS = [
  { id: 'gantry', kind: 'AMANECER · SKYLINE', tags: ['Amanecer', 'Skyline'], stars: 5, when: 'sunrise' },
  { id: 'tudor', kind: 'MAÑANA · CALLE', tags: ['Calle', 'Arquitectura'], stars: 4, when: '09:30' },
  { id: 'oculus', kind: 'ARQUITECTURA', tags: ['Arquitectura'], stars: 4, when: '11:00' },
  { id: 'moynihan', kind: 'ARQUITECTURA · LUZ CENITAL', tags: ['Arquitectura'], stars: 4, when: '12:30' },
  { id: 'chinatown', kind: 'CALLE · DOYERS ST', tags: ['Calle'], stars: 4, when: '13:00' },
  { id: 'soho', kind: 'ARQUITECTURA · HIERRO FUNDIDO', tags: ['Arquitectura', 'Calle'], stars: 4, when: '15:00' },
  { id: 'highline', kind: 'HORA DORADA', tags: ['Atardecer'], stars: 4, when: 'golden' },
  { id: 'dumbo', kind: 'ATARDECER · ARQUITECTURA', tags: ['Atardecer', 'Arquitectura'], stars: 5, when: 'sunset' },
  { id: 'edge', kind: 'ATARDECER · SKYLINE', tags: ['Atardecer', 'Skyline'], stars: 5, when: 'sunset' },
  { id: 'topofrock', kind: 'ATARDECER · SKYLINE', tags: ['Atardecer', 'Skyline', 'Noche'], stars: 5, when: 'sunset' },
  { id: 'bbpark', kind: 'HORA AZUL · SKYLINE', tags: ['Hora azul', 'Skyline'], stars: 5, when: 'blue' },
  { id: 'queensbridge', kind: 'HORA AZUL · SKYLINE', tags: ['Hora azul', 'Skyline'], stars: 5, when: 'blue' },
  { id: 'brooklynheights', kind: 'HORA AZUL · SKYLINE', tags: ['Hora azul', 'Skyline'], stars: 5, when: 'blue' },
  { id: 'tkts', kind: 'NOCHE · CALLE', tags: ['Noche', 'Calle'], stars: 3, when: '21:30' },
  { id: 'gct', kind: 'NOCHE · ARQUITECTURA', tags: ['Noche', 'Arquitectura'], stars: 4, when: '22:30' },
];

const HAPPY_HOUR = { site: 'https://5pm.nyc', hoods: { 'West Village': 'west-village', 'Greenwich Village': 'west-village', 'East Village': 'east-village', 'Lower East Side': 'lower-east-side', Chelsea: 'chelsea', Meatpacking: 'chelsea', Midtown: 'midtown', 'Midtown East': 'midtown-east', 'Garment District': 'midtown', "Hell's Kitchen": 'hells-kitchen', SoHo: 'soho', Nolita: 'soho', NoHo: 'east-village', Tribeca: 'soho', 'Financial District': 'financial-district', 'Stone St': 'financial-district', Williamsburg: 'williamsburg', Bushwick: 'bushwick', 'Grand Central': 'midtown-east', 'Upper East Side': 'upper-east-side', 'Upper West Side': 'upper-west-side', Harlem: 'harlem', 'Union Square': 'union-square', 'Times Square': 'midtown' } };

const BUDGET_SHARE = { Comida: ['Café', 'Comida', 'Pizza', 'Almuerzo', 'Cena', 'Mercado'], Compras: ['Compras'], Noche: ['Bar', 'Jazz', 'Club', 'Rooftop', 'Teatro', 'Comedia'] };
